### ISSUE TITLE
Hide node_modules and other known ignorable files.

### ISSUE THREAD

**Issue by josead** [metacall/deploy#144]
When doing deployment,  node_modules appears under file selection, is not so intuitive to go up in the list to select the files that are not on node_modules.

I propose we hide folders of this nature or we simply put them at the bottom, leaving the most relevant at the top.

**Comment by Creatoon** [comment]
@josead Hey, thanks for reporting this, the thing is there is no need of selection of node_modules, so we can hide it completely, it will be more cool if you provide a screenshot here.

**Comment by Creatoon** [comment]
@josead [Ignore Files](https://github.com/metacall/deploy#ignore-files)
