### ISSUE TITLE
feat: add setupcheck function

### ISSUE THREAD

**Issue by Creatoon** [metacall/deploy#146]
We need some enviroment variables while testing and there is a possiblity that dev won't add .env file and running tests without those env vars will be useless.

So this function will check for every enviroment var we need while testing and if succeed then we will run the tests and if not we will simply skip those tests by raising a failure with a message "Env not found or whatever".

**Comment by GaurKS** [comment]
hey @Creatoon, can you assign this task to me. I am already into it.

**Comment by Creatoon** [comment]
@GaurKS Sure go ahead
