### ISSUE TITLE
change old twitter logo to new x logo

### ISSUE THREAD

**Issue by nilaygit-10721** [metacall/deploy#169]
![image](https://github.com/user-attachments/assets/3172e965-0a5f-424d-949d-c8edafc4ccb5)

**Comment by IamAyrush** [comment]
Hi Team,

I hope you're doing well! I believe resolving this issue would be a great way for me to start contributing. Could you please assign it to me?

Looking forward to working on it.

**Comment by DevMittal09** [comment]
Hey, I'm interested to work on this issues and if its still available can you assign it to me?
