### ISSUE TITLE
Bug: dependency of a dependency error

### ISSUE THREAD

**Issue by itsritiksingh** [metacall/deploy#48]
For installing metacall:protocol you need to install 2 extra package 

- @types/ignore-walk
- @types/jsonwebtoken

these 2 packages are already devdepencies of metacall/protocol

**Comment by viferga** [comment]
Solved:
https://github.com/metacall/protocol/commit/d5fafb7d843ebb552cab50d8acc84243f39ad0ad
https://github.com/metacall/deploy/commit/2390fb3566d9a7bd2e77bc207899f38b2873d2ff
