### ISSUE TITLE
Add remaining tests

### ISSUE THREAD

**Issue by viferga** [metacall/deploy#73]
https://github.com/metacall/deploy/blob/605258cf7c063a3b4d02bbb29aad8d951c2c701f/src/test/cli.integration.spec.ts#L159

**Comment by parteekcoder** [comment]
@viferga i would like to work upon this issue

**Comment by Creatoon** [comment]
No tests pending.

**Comment by parteekcoder** [comment]
@Creatoon can you give me some improvements or issue to be done on this repo, I would like to contribute in GSOC for this project , by contributing I can understand it better

**Comment by Creatoon** [comment]
@parteekcoder Use it and if you find any improvement or bugs, raise a pr or open an issue.
